# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jvasquez <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/13 17:31:12 by jvasquez          #+#    #+#              #
#    Updated: 2022/07/21 21:52:50 by jvasquez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CFLAGS = -Wall -Wextra -Werror
FUNCTIONS = ft_isalpha.c		\
		   	ft_isdigit.c		\
		   	ft_isalnum.c		\
		   	ft_isascii.c		\
		   	ft_isprint.c		\
		   	ft_strlen.c			\
			ft_memset.c			\
			ft_bzero.c			\
			ft_memcpy.c			\
			ft_memmove.c		\
			ft_strlcpy.c		\
			ft_strlcat.c		\
		   	ft_toupper.c		\
		   	ft_tolower.c		\
		   	ft_strchr.c			\
		   	ft_strrchr.c		\
		   	ft_strncmp.c		\
			ft_memchr.c			\
			ft_memcmp.c			\
		   	ft_strnstr.c		\
		   	ft_atoi.c			\
			ft_calloc.c			\
			ft_strdup.c			\
			ft_substr.c			\
			ft_strjoin.c		\
			ft_split.c			\
			ft_itoa.c			\
			ft_strtrim.c		\
			ft_strmapi.c		\
			ft_putchar_fd.c		\
			ft_putstr_fd.c		\
			ft_putendl_fd.c 	\
			ft_putnbr_fd.c		\
			ft_striteri.c		\

FBONUS =	ft_lstnew_bonus.c		\
			ft_lstadd_front_bonus.c	\
			ft_lstadd_back_bonus.c	\
			ft_lstlast_bonus.c		\
			ft_lstsize_bonus.c		\
			ft_lstdelone_bonus.c	\
			ft_lstclear_bonus.c		\
			ft_lstiter_bonus.c		\
			ft_lstmap_bonus.c		\

OBJS = ${FUNCTIONS:.c=.o}
OBJB = ${FBONUS:.c=.o}

#.c.o:
#			gcc -I $(FLAGS) -c $< -o ${<:.c=.o}

${NAME}:	${OBJS}
			ar rcs ${NAME} ${OBJS} 

all: $(NAME)

clean:
			rm -f $(OBJS) $(OBJB)

fclean: clean
			rm -f $(NAME)

bonus:		
			make "OBJS = $(OBJB)"

re: fclean all
